# Based on https://github.com/hashicorp/tfc-workflows-github/blob/main/workflows/terraform-cloud.apply-run.workflow.yml
---
name: Terraform Cloud Apply Run

on: workflow_dispatch

env:
  TF_CLOUD_ORGANIZATION: "lmhd"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"

jobs:
  apply:
    strategy:
      fail-fast: false
      matrix:
        workspace:
          - vault
          - vault-okta
          - tfc-jwt-test
          - aws-sso
          - better-uptime
          - dns
          - bootstrap-aws_creds-lmhd_root
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.2
        id: create-run
        with:
          workspace: ${{ matrix.workspace }}